# -*- coding: utf-8 -*-
import json

lessons = [
    {
        "id": "n5_b7",
        "title": "Bài 7: Động từ sơ cấp, Gia đình & Đồ dùng",
        "description": "Động từ V1/V2/V3 (học, rửa, mua, viết, nghe...), thành viên gia đình và mở rộng danh từ động từ する",
        "words": [
            # 7_1 Verbs
            {"kanji": "習う", "hiragana": "ならう", "vietnamese": "Học (tiếng Nhật)", "group": 1},
            {"kanji": "洗う", "hiragana": "あらう", "vietnamese": "Rửa (mặt)", "group": 1},
            {"kanji": "買う", "hiragana": "かう", "vietnamese": "Mua (trái cây)", "group": 1},
            {"kanji": "書く", "hiragana": "かく", "vietnamese": "Viết (thư)", "group": 1},
            {"kanji": "聞く", "hiragana": "きく", "vietnamese": "Nghe (nhạc)", "group": 1},
            {"kanji": "話す", "hiragana": "はなす", "vietnamese": "Nói chuyện (tiếng Nhật)", "group": 1},
            {"kanji": "読む", "hiragana": "よむ", "vietnamese": "Đọc (báo)", "group": 1},
            {"kanji": "飲む", "hiragana": "のむ", "vietnamese": "Uống (trà)", "group": 1},
            {"kanji": "作る", "hiragana": "つくる", "vietnamese": "Nấu (món ăn), làm", "group": 1},
            {"kanji": "行く", "hiragana": "いく", "vietnamese": "Đi (công viên)", "group": 1},
            {"kanji": "帰る", "hiragana": "かえる", "vietnamese": "Về (nhà)", "group": 1},
            {"kanji": "戻る", "hiragana": "もどる", "vietnamese": "Quay lại (phòng)", "group": 1},
            {"kanji": "教える", "hiragana": "おしえる", "vietnamese": "Chỉ, dạy (tiếng Nhật)", "group": 2},
            {"kanji": "食べる", "hiragana": "たべる", "vietnamese": "Ăn (cơm)", "group": 2},
            {"kanji": "見る", "hiragana": "みる", "vietnamese": "Xem (tivi)", "group": 2},
            {"kanji": "する", "hiragana": "する", "vietnamese": "Làm (bài tập, việc, tiệc, thể thao)", "group": 3},
            {"kanji": "来る", "hiragana": "くる", "vietnamese": "Đến (trường)", "group": 3},
            # 7_1 Nouns
            {"kanji": "顔", "hiragana": "かお", "vietnamese": "Mặt"},
            {"kanji": "手紙", "hiragana": "てがみ", "vietnamese": "Lá thư"},
            {"kanji": "日記", "hiragana": "にっき", "vietnamese": "Nhật ký (NHẬT KÝ)"},
            {"kanji": "音楽", "hiragana": "おんがく", "vietnamese": "Âm nhạc (ÂM NHẠC)"},
            {"kanji": "映画", "hiragana": "えいが", "vietnamese": "Phim (ÁNH HỌA)"},
            {"kanji": "水", "hiragana": "みず", "vietnamese": "Nước"},
            {"kanji": "お茶", "hiragana": "おちゃ", "vietnamese": "Trà"},
            {"kanji": "牛乳", "hiragana": "ぎゅうにゅう", "vietnamese": "Sữa bò (NGƯU NHŨ)"},
            {"kanji": "ご飯", "hiragana": "ごはん", "vietnamese": "Cơm (PHẠN)"},
            {"kanji": "朝ご飯", "hiragana": "あさごはん", "vietnamese": "Cơm sáng"},
            {"kanji": "昼ご飯", "hiragana": "ひるごはん", "vietnamese": "Cơm trưa"},
            {"kanji": "晩ご飯", "hiragana": "ばんごはん", "vietnamese": "Cơm tối"},
            {"kanji": "卵", "hiragana": "たまご", "vietnamese": "Trứng"},
            {"kanji": "果物", "hiragana": "くだもの", "vietnamese": "Trái cây"},
            {"kanji": "国", "hiragana": "くに", "vietnamese": "Đất nước"},
            # 7_2 Nouns & Family
            {"kanji": "飛行機", "hiragana": "ひこうき", "vietnamese": "Máy bay (PHI HÀNH CƠ)"},
            {"kanji": "新幹線", "hiragana": "しんかんせん", "vietnamese": "Tàu cao tốc (TÂN CÁN TUYẾN)"},
            {"kanji": "船", "hiragana": "ふね", "vietnamese": "Thuyền"},
            {"kanji": "箸", "hiragana": "はし", "vietnamese": "Đôi đũa"},
            {"kanji": "家族", "hiragana": "かぞく", "vietnamese": "Gia đình (GIA TỘC)"},
            {"kanji": "両親", "hiragana": "りょうしん", "vietnamese": "Bố mẹ (LƯỠNG THÂN)"},
            {"kanji": "父", "hiragana": "ちち", "vietnamese": "Bố (mình)"},
            {"kanji": "お父さん", "hiragana": "おとうさん", "vietnamese": "Bố (người khác)"},
            {"kanji": "母", "hiragana": "はは", "vietnamese": "Mẹ (mình)"},
            {"kanji": "お母さん", "hiragana": "おかあさん", "vietnamese": "Mẹ (người khác)"},
            {"kanji": "兄弟", "hiragana": "きょうだい", "vietnamese": "Anh chị em (HUYNH ĐỆ)"},
            {"kanji": "兄", "hiragana": "あに", "vietnamese": "Anh trai (mình)"},
            {"kanji": "お兄さん", "hiragana": "おにいさん", "vietnamese": "Anh trai (người khác)"},
            {"kanji": "弟", "hiragana": "おとうと", "vietnamese": "Em trai (mình)"},
            {"kanji": "おとうとさん", "hiragana": "おとうとさん", "vietnamese": "Em trai (người khác)"},
            {"kanji": "姉", "hiragana": "あね", "vietnamese": "Chị gái (mình)"},
            {"kanji": "お姉さん", "hiragana": "おねえさん", "vietnamese": "Chị gái (người khác)"},
            {"kanji": "妹", "hiragana": "いもうと", "vietnamese": "Em gái (mình)"},
            {"kanji": "いもうとさん", "hiragana": "いもうとさん", "vietnamese": "Em gái (người khác)"},
            {"kanji": "親友", "hiragana": "しんゆう", "vietnamese": "Bạn thân (THÂN HỮU)"},
            {"kanji": "友達", "hiragana": "ともだち", "vietnamese": "Bạn bè"},
            {"kanji": "恋人", "hiragana": "こいびと", "vietnamese": "Người yêu"},
            {"kanji": "会社の人", "hiragana": "かいしゃのひと", "vietnamese": "Người cùng công ty"},
            {"kanji": "一人で", "hiragana": "ひとりで", "vietnamese": "Một mình"},
            {"kanji": "週末", "hiragana": "しゅうまつ", "vietnamese": "Cuối tuần (CHU MẠT)"},
            {"kanji": "", "hiragana": "テレビ", "vietnamese": "Tivi"},
            {"kanji": "", "hiragana": "アニメ", "vietnamese": "Phim hoạt hình"},
            {"kanji": "", "hiragana": "レポート", "vietnamese": "Bài báo cáo"},
            {"kanji": "", "hiragana": "ミルクティー", "vietnamese": "Trà sữa"},
            {"kanji": "", "hiragana": "ジュース", "vietnamese": "Nước ép trái cây"},
            {"kanji": "", "hiragana": "コーヒー", "vietnamese": "Cà phê"},
            {"kanji": "", "hiragana": "ビール", "vietnamese": "Bia"},
            {"kanji": "", "hiragana": "パン", "vietnamese": "Bánh mì"},
            {"kanji": "", "hiragana": "サッカー", "vietnamese": "Bóng đá"},
            {"kanji": "", "hiragana": "テニス", "vietnamese": "Quần vợt, tennis"},
            {"kanji": "", "hiragana": "スーパー", "vietnamese": "Siêu thị"},
            {"kanji": "", "hiragana": "コンビニ", "vietnamese": "Cửa hàng tiện lợi"},
            {"kanji": "", "hiragana": "スプーン", "vietnamese": "Cái muỗng"},
            {"kanji": "", "hiragana": "フォーク", "vietnamese": "Cái nĩa"},
            {"kanji": "", "hiragana": "ナイフ", "vietnamese": "Con dao"},
            {"kanji": "", "hiragana": "ユーチューブ", "vietnamese": "Youtube"},
            # 7_3 Extended Suru Verbs
            {"kanji": "勉強", "hiragana": "べんきょう（をする）", "vietnamese": "Học"},
            {"kanji": "練習", "hiragana": "れんしゅう（をする）", "vietnamese": "Luyện tập"},
            {"kanji": "相談", "hiragana": "そうだん（をする）", "vietnamese": "Trao đổi, tham khảo ý kiến"},
            {"kanji": "留学", "hiragana": "りゅうがく（をする）", "vietnamese": "Du học"},
            {"kanji": "料理", "hiragana": "りょうり（をする）", "vietnamese": "Nấu món ăn"},
            {"kanji": "食事", "hiragana": "しょくじ（をする）", "vietnamese": "Dùng bữa"},
            {"kanji": "買い物", "hiragana": "かいもの（をする）", "vietnamese": "Mua sắm"},
            {"kanji": "散歩", "hiragana": "さんぽ（をする）", "vietnamese": "Đi dạo"},
            {"kanji": "掃除", "hiragana": "そうじ（をする）", "vietnamese": "Quét dọn"},
            {"kanji": "洗濯", "hiragana": "せんたく（をする）", "vietnamese": "Giặt giũ"},
            {"kanji": "運動", "hiragana": "うんどう（をする）", "vietnamese": "Tập thể dục"},
            {"kanji": "運転", "hiragana": "うんてん（をする）", "vietnamese": "Lái xe"},
            {"kanji": "旅行", "hiragana": "りょこう（をする）", "vietnamese": "Du lịch"},
            {"kanji": "出張", "hiragana": "しゅっちょう（をする）", "vietnamese": "Đi công tác"},
            {"kanji": "結婚", "hiragana": "けっこん（をする）", "vietnamese": "Kết hôn"},
            {"kanji": "", "hiragana": "カラオケ（をする）", "vietnamese": "Hát karaoke"},
            {"kanji": "", "hiragana": "ジョギング（をする）", "vietnamese": "Chạy bộ"},
            {"kanji": "", "hiragana": "ハイキング（をする）", "vietnamese": "Đi chơi dã ngoại"}
        ]
    },
    {
        "id": "n5_b8",
        "title": "Bài 8: Phương tiện & Bút viết, Biến đổi đuôi câu",
        "description": "Phương tiện di chuyển, dụng cụ viết và quy tắc biến đổi lịch sự / thân mật",
        "words": [
            {"kanji": "", "hiragana": "オートバイ", "vietnamese": "Xe máy, xe môtô"},
            {"kanji": "", "hiragana": "バス", "vietnamese": "Xe buýt"},
            {"kanji": "", "hiragana": "タクシー", "vietnamese": "Xe taxi"},
            {"kanji": "", "hiragana": "ペン", "vietnamese": "Bút, bút máy"},
            {"kanji": "", "hiragana": "ボールペン", "vietnamese": "Bút bi"},
            {"kanji": "", "hiragana": "シャープペンシル", "vietnamese": "Bút chì bấm"},
            {"kanji": "", "hiragana": "スプーン", "vietnamese": "Cái muỗng"},
            {"kanji": "", "hiragana": "フォーク", "vietnamese": "Cái nĩa"},
            {"kanji": "", "hiragana": "ナイフ", "vietnamese": "Con dao"},
            {"kanji": "一日", "hiragana": "いちにち", "vietnamese": "Một ngày (NHẤT NHẬT)"},
            {"kanji": "", "hiragana": "いつも", "vietnamese": "Lúc nào cũng, thường hay"},
            {"kanji": "", "hiragana": "よく", "vietnamese": "Thường, rõ, kỹ"},
            {"kanji": "", "hiragana": "それから", "vietnamese": "Sau đó"}
        ]
    },
    {
        "id": "n5_b9",
        "title": "Bài 9: Tính từ, Thời gian & Hoạt động",
        "description": "Chụp ảnh, các tính từ nóng/lạnh/ấm/mát/vui/bận, mốc thời gian theo tuần và phó từ",
        "words": [
            {"kanji": "写真を撮る", "hiragana": "しゃしんをとる", "vietnamese": "Chụp ảnh", "group": 1},
            {"kanji": "暑い", "hiragana": "あつい", "vietnamese": "Nóng"},
            {"kanji": "寒い", "hiragana": "さむい", "vietnamese": "Lạnh"},
            {"kanji": "暖かい", "hiragana": "あたたかい", "vietnamese": "Ấm"},
            {"kanji": "涼しい", "hiragana": "すずしい", "vietnamese": "Mát"},
            {"kanji": "楽しい", "hiragana": "たのしい", "vietnamese": "Vui"},
            {"kanji": "忙しい", "hiragana": "いそがしい", "vietnamese": "Bận rộn"},
            {"kanji": "暇", "hiragana": "ひま", "vietnamese": "Rảnh rỗi"},
            {"kanji": "簡単", "hiragana": "かんたん", "vietnamese": "Đơn giản"},
            {"kanji": "複雑", "hiragana": "ふくざつ", "vietnamese": "Phức tạp"},
            {"kanji": "先々週", "hiragana": "せんせんしゅう", "vietnamese": "Tuần trước nữa"},
            {"kanji": "先週", "hiragana": "せんしゅう", "vietnamese": "Tuần trước (TIÊN CHU)"},
            {"kanji": "今週", "hiragana": "こんしゅう", "vietnamese": "Tuần này (KIM CHU)"},
            {"kanji": "来週", "hiragana": "らいしゅう", "vietnamese": "Tuần tới (LAI CHU)"},
            {"kanji": "再来週", "hiragana": "さらいしゅう", "vietnamese": "Tuần tới nữa"},
            {"kanji": "今朝", "hiragana": "けさ", "vietnamese": "Sáng nay"},
            {"kanji": "夕べ", "hiragana": "ゆうべ", "vietnamese": "Tối qua"},
            {"kanji": "昔", "hiragana": "むかし", "vietnamese": "Ngày xưa"},
            {"kanji": "天気", "hiragana": "てんき", "vietnamese": "Thời tiết (THIÊN KHÍ)"},
            {"kanji": "", "hiragana": "へん", "vietnamese": "Vùng, khu vực"},
            {"kanji": "赤ちゃん", "hiragana": "あかちゃん", "vietnamese": "Em bé"},
            {"kanji": "", "hiragana": "テスト", "vietnamese": "Bài kiểm tra"},
            {"kanji": "", "hiragana": "パーティー", "vietnamese": "Bữa tiệc"},
            {"kanji": "", "hiragana": "レストラン", "vietnamese": "Nhà hàng"},
            {"kanji": "", "hiragana": "カラオケ", "vietnamese": "Karaoke"},
            {"kanji": "もう", "hiragana": "もう", "vietnamese": "Đã, rồi"},
            {"kanji": "まだ", "hiragana": "まだ", "vietnamese": "Chưa, vẫn"},
            {"kanji": "これから / いまから", "hiragana": "これから / いまから", "vietnamese": "Từ bây giờ"},
            {"kanji": "一緒に", "hiragana": "いっしょに", "vietnamese": "Cùng nhau"},
            {"kanji": "また", "hiragana": "また", "vietnamese": "Lại, nữa"},
            {"kanji": "大人", "hiragana": "おとな", "vietnamese": "Người lớn"},
            {"kanji": "子供", "hiragana": "こども", "vietnamese": "Trẻ con, con cái"},
            {"kanji": "切符", "hiragana": "きっぷ", "vietnamese": "Vé"},
            {"kanji": "花見", "hiragana": "はなみ", "vietnamese": "Việc ngắm hoa"}
        ]
    },
    {
        "id": "n5_b10",
        "title": "Bài 10: Thời gian, Gia đình & Đơn vị thời lượng",
        "description": "Động từ tốn thời gian/tiền bạc, đánh răng, các kỳ nghỉ, bảng thời lượng (giờ, ngày, tuần, tháng)",
        "words": [
            {"kanji": "掛かる", "hiragana": "かかる", "vietnamese": "Tốn (thời gian, tiền)", "group": 1},
            {"kanji": "始まる", "hiragana": "はじまる", "vietnamese": "(giờ học) Bắt đầu", "group": 1},
            {"kanji": "終わる", "hiragana": "おわる", "vietnamese": "(giờ học) Kết thúc", "group": 1},
            {"kanji": "磨く", "hiragana": "みがく", "vietnamese": "Đánh (răng)", "group": 1},
            {"kanji": "受ける", "hiragana": "うける", "vietnamese": "Kiểm tra sức khỏe, tham gia thi", "group": 2},
            {"kanji": "毎朝", "hiragana": "まいあさ", "vietnamese": "Mỗi sáng (MỖI TRIÊU)"},
            {"kanji": "毎晩", "hiragana": "まいばん", "vietnamese": "Mỗi tối (MỖI VÃN)"},
            {"kanji": "毎日", "hiragana": "まいにち", "vietnamese": "Mỗi ngày (MỖI NHẬT)"},
            {"kanji": "毎週", "hiragana": "まいしゅう", "vietnamese": "Mỗi tuần (MỖI CHU)"},
            {"kanji": "毎月", "hiragana": "まいつき", "vietnamese": "Mỗi tháng (MỖI NGUYỆT)"},
            {"kanji": "毎年", "hiragana": "まいとし", "vietnamese": "Mỗi năm (MỖI NIÊN)"},
            {"kanji": "お正月", "hiragana": "おしょうがつ", "vietnamese": "Tết (CHÍNH NGUYỆT)"},
            {"kanji": "春休み", "hiragana": "はるやすみ", "vietnamese": "Nghỉ xuân"},
            {"kanji": "夏休み", "hiragana": "なつやすみ", "vietnamese": "Nghỉ hè"},
            {"kanji": "冬休み", "hiragana": "ふゆやすみ", "vietnamese": "Nghỉ đông"},
            {"kanji": "高速船", "hiragana": "こうそくせん", "vietnamese": "Tàu cánh ngầm cao tốc"},
            {"kanji": "～回", "hiragana": "～かい", "vietnamese": "~ Lần (HỒI)"},
            {"kanji": "何回", "hiragana": "なんかい", "vietnamese": "Bao nhiêu lần?"},
            {"kanji": "疲れる", "hiragana": "つかれる", "vietnamese": "Mệt", "group": 2},
            {"kanji": "お祭り", "hiragana": "おまつり", "vietnamese": "Lễ hội"},
            {"kanji": "", "hiragana": "グラブ", "vietnamese": "Xe Grab"},
            {"kanji": "", "hiragana": "アルバイト", "vietnamese": "Việc làm thêm"},
            {"kanji": "", "hiragana": "バドミントン", "vietnamese": "Cầu lông"},
            {"kanji": "", "hiragana": "ジム", "vietnamese": "Phòng tập Gym"},
            {"kanji": "どのぐらい / どのくらい", "hiragana": "どのぐらい / どのくらい", "vietnamese": "Khoảng bao lâu / bao nhiêu"}
        ]
    },
    {
        "id": "n5_b11",
        "title": "Bài 11: Động từ & Trợ từ chuyển động, Nơi chốn",
        "description": "Đi kèm trợ từ に / から / を / と: vào, lên, xuống, rời, leo núi, bay trên trời, băng qua cầu...",
        "words": [
            {"kanji": "聞く", "hiragana": "きく", "vietnamese": "Hỏi (giáo viên)", "group": 1},
            {"kanji": "貸す", "hiragana": "かす", "vietnamese": "Cho mượn, cho thuê", "group": 1},
            {"kanji": "出す", "hiragana": "だす", "vietnamese": "Nộp, gửi (báo cáo)", "group": 1},
            {"kanji": "返す", "hiragana": "かえす", "vietnamese": "Trả lại (sách)", "group": 1},
            {"kanji": "送る", "hiragana": "おくる", "vietnamese": "Gửi (email)", "group": 1},
            {"kanji": "見せる", "hiragana": "みせる", "vietnamese": "Cho xem (ảnh)", "group": 2},
            {"kanji": "電話を掛ける", "hiragana": "でんわをかける", "vietnamese": "Gọi điện thoại", "group": 2},
            {"kanji": "借りる", "hiragana": "かりる", "vietnamese": "Mượn, vay, thuê (từ ai)", "group": 2},
            {"kanji": "入る", "hiragana": "はいる", "vietnamese": "Vào (phòng học)", "group": 1},
            {"kanji": "乗る", "hiragana": "のる", "vietnamese": "Lên (xe), cưỡi (ngựa)", "group": 1},
            {"kanji": "登る", "hiragana": "のぼる", "vietnamese": "Leo (núi)", "group": 1},
            {"kanji": "着く", "hiragana": "つく", "vietnamese": "Đến (sân bay)", "group": 1},
            {"kanji": "出る", "hiragana": "でる", "vietnamese": "Rời khỏi (nhà)", "group": 2},
            {"kanji": "降りる", "hiragana": "おりる", "vietnamese": "Xuống (xe)", "group": 2},
            {"kanji": "卒業する", "hiragana": "そつぎょうする", "vietnamese": "Tốt nghiệp (đại học)", "group": 3},
            {"kanji": "出発する", "hiragana": "しゅっぱつする", "vietnamese": "Xuất phát, rời (sân bay)", "group": 3},
            {"kanji": "言葉", "hiragana": "ことば", "vietnamese": "Từ, ngôn ngữ"},
            {"kanji": "意味", "hiragana": "いみ", "vietnamese": "Ý nghĩa"},
            {"kanji": "お金", "hiragana": "おかね", "vietnamese": "Tiền"},
            {"kanji": "部長", "hiragana": "ぶちょう", "vietnamese": "Trưởng phòng (BỘ TRƯỞNG)"},
            {"kanji": "課長", "hiragana": "かちょう", "vietnamese": "Trưởng ban"},
            {"kanji": "話", "hiragana": "はなし", "vietnamese": "Câu chuyện"},
            {"kanji": "お風呂", "hiragana": "おふろ", "vietnamese": "Bồn tắm"},
            {"kanji": "", "hiragana": "メール", "vietnamese": "Thư điện tử"},
            # 11_2 Extended Verbs
            {"kanji": "飛ぶ", "hiragana": "とぶ", "vietnamese": "Bay (trên bầu trời)", "group": 1},
            {"kanji": "走る", "hiragana": "はしる", "vietnamese": "Chạy (trên đường)", "group": 1},
            {"kanji": "通る", "hiragana": "とおる", "vietnamese": "Đi qua (đường)", "group": 1},
            {"kanji": "渡る", "hiragana": "わたる", "vietnamese": "Băng qua (cầu)", "group": 1},
            {"kanji": "歩く", "hiragana": "あるく", "vietnamese": "Đi bộ (trong công viên)", "group": 1},
            {"kanji": "立つ", "hiragana": "たつ", "vietnamese": "Đứng (ở lối vào)", "group": 1},
            {"kanji": "座る", "hiragana": "すわる", "vietnamese": "Ngồi (ở đằng kia)", "group": 1},
            {"kanji": "泊まる", "hiragana": "とまる", "vietnamese": "Trọ lại, ngủ lại (khách sạn)", "group": 1},
            {"kanji": "止まる", "hiragana": "とまる", "vietnamese": "Dừng, đậu (mỗi ga)", "group": 1},
            {"kanji": "置く", "hiragana": "おく", "vietnamese": "Đặt, để (xe đạp ở...)", "group": 1},
            {"kanji": "貼る", "hiragana": "はる", "vietnamese": "Dán tem (vào phong bì)", "group": 1},
            {"kanji": "入れる", "hiragana": "いれる", "vietnamese": "Bỏ (bia vào tủ lạnh)", "group": 2},
            {"kanji": "掛ける", "hiragana": "かける", "vietnamese": "Treo (lịch lên tường)", "group": 2},
            {"kanji": "答える", "hiragana": "こたえる", "vietnamese": "Trả lời (cho...)", "group": 2},
            {"kanji": "質問する", "hiragana": "しつもんする", "vietnamese": "Đặt câu hỏi", "group": 3},
            {"kanji": "別れる", "hiragana": "わかれる", "vietnamese": "Chia tay (với...)", "group": 2},
            {"kanji": "試合をする", "hiragana": "しあいをする", "vietnamese": "Thi đấu", "group": 3},
            {"kanji": "戦争をする", "hiragana": "せんそうをする", "vietnamese": "Chiến đấu", "group": 3}
        ]
    },
    {
        "id": "n5_b12",
        "title": "Bài 12: Vị trí, Động vật, Trái cây & Số đếm",
        "description": "Từ chỉ vị trí, con vật, trái cây, đồ vật trong nhà và bảng đơn vị đếm (cái, người, cuốn, tờ, chiếc, con...)",
        "words": [
            # Location
            {"kanji": "上 / 下", "hiragana": "うえ / した", "vietnamese": "Phía trên / Phía dưới"},
            {"kanji": "前 / 後ろ", "hiragana": "まえ / うしろ", "vietnamese": "Phía trước / Phía sau"},
            {"kanji": "右 / 左", "hiragana": "みぎ / ひだり", "vietnamese": "Bên phải / Bên trái"},
            {"kanji": "中 / 外", "hiragana": "なか / そと", "vietnamese": "Bên trong / Bên ngoài"},
            {"kanji": "隣", "hiragana": "となり", "vietnamese": "Bên cạnh, sát bên"},
            {"kanji": "横", "hiragana": "よこ", "vietnamese": "Bên cạnh, bên hông"},
            {"kanji": "側", "hiragana": "そば", "vietnamese": "Bên cạnh"},
            {"kanji": "間", "hiragana": "あいだ", "vietnamese": "Ở giữa"},
            {"kanji": "近く", "hiragana": "ちかく", "vietnamese": "Gần, chỗ gần"},
            {"kanji": "遠く", "hiragana": "とおく", "vietnamese": "Phía xa, đằng xa"},
            {"kanji": "向こう", "hiragana": "むこう", "vietnamese": "Phía bên kia"},
            # Animals
            {"kanji": "猫", "hiragana": "ねこ", "vietnamese": "Mèo"},
            {"kanji": "犬", "hiragana": "いぬ", "vietnamese": "Chó"},
            {"kanji": "鳥", "hiragana": "とり", "vietnamese": "Chim"},
            {"kanji": "小鳥", "hiragana": "ことり", "vietnamese": "Chim nhỏ"},
            {"kanji": "鶏", "hiragana": "にわとり", "vietnamese": "Gà"},
            {"kanji": "魚", "hiragana": "さかな", "vietnamese": "Cá"},
            {"kanji": "鼠", "hiragana": "ねずみ", "vietnamese": "Chuột"},
            {"kanji": "蟹", "hiragana": "かに", "vietnamese": "Cua"},
            {"kanji": "牛", "hiragana": "うし", "vietnamese": "Bò"},
            {"kanji": "馬", "hiragana": "うま", "vietnamese": "Ngựa"},
            {"kanji": "兎", "hiragana": "うさぎ", "vietnamese": "Thỏ"},
            {"kanji": "亀", "hiragana": "かめ", "vietnamese": "Rùa"},
            {"kanji": "象", "hiragana": "ぞう", "vietnamese": "Voi"},
            {"kanji": "", "hiragana": "キリン", "vietnamese": "Hươu cao cổ"},
            {"kanji": "", "hiragana": "ライオン", "vietnamese": "Sư tử"},
            {"kanji": "", "hiragana": "パンダ", "vietnamese": "Gấu trúc"},
            # Fruits
            {"kanji": "林檎", "hiragana": "りんご", "vietnamese": "Táo"},
            {"kanji": "蜜柑", "hiragana": "みかん", "vietnamese": "Quýt"},
            {"kanji": "柿", "hiragana": "かき", "vietnamese": "Hồng"},
            {"kanji": "桃", "hiragana": "もも", "vietnamese": "Đào"},
            {"kanji": "梨", "hiragana": "なし", "vietnamese": "Lê"},
            {"kanji": "西瓜", "hiragana": "すいか", "vietnamese": "Dưa hấu"},
            {"kanji": "葡萄", "hiragana": "ぶどう", "vietnamese": "Nho"},
            {"kanji": "苺", "hiragana": "いちご", "vietnamese": "Dâu"},
            {"kanji": "", "hiragana": "バナナ", "vietnamese": "Chuối"},
            {"kanji": "", "hiragana": "マンゴー", "vietnamese": "Xoài"},
            {"kanji": "", "hiragana": "メロン", "vietnamese": "Dưa lưới"},
            {"kanji": "", "hiragana": "オレンジ", "vietnamese": "Cam"},
            {"kanji": "", "hiragana": "ドリアン", "vietnamese": "Sầu riêng"},
            {"kanji": "", "hiragana": "ココナッツ", "vietnamese": "Dừa"},
            {"kanji": "", "hiragana": "パイナップル", "vietnamese": "Dứa, thơm"},
            {"kanji": "", "hiragana": "パパイヤ", "vietnamese": "Đu đủ"},
            # Verbs & Nouns
            {"kanji": "ある", "hiragana": "ある", "vietnamese": "Có, ở (đồ vật)", "group": 1},
            {"kanji": "いる", "hiragana": "いる", "vietnamese": "Có, ở (người, động vật)", "group": 2},
            {"kanji": "職員室", "hiragana": "しょくいんしつ", "vietnamese": "Phòng giáo viên"},
            {"kanji": "交番", "hiragana": "こうばん", "vietnamese": "Đồn công an (GIAO PHIÊN)"},
            {"kanji": "本棚", "hiragana": "ほんだな", "vietnamese": "Kệ sách"},
            {"kanji": "子供たち", "hiragana": "こどもたち", "vietnamese": "Bọn trẻ"},
            {"kanji": "枝", "hiragana": "えだ", "vietnamese": "Cành cây"},
            {"kanji": "屋根", "hiragana": "やね", "vietnamese": "Mái nhà"},
            {"kanji": "", "hiragana": "たんす", "vietnamese": "Tủ quần áo"},
            {"kanji": "", "hiragana": "トイレ", "vietnamese": "Nhà vệ sinh"},
            {"kanji": "", "hiragana": "シャツ", "vietnamese": "Áo sơ mi"},
            # Extended
            {"kanji": "会場", "hiragana": "かいじょう", "vietnamese": "Hội trường (HỘI TRƯỜNG)"},
            {"kanji": "屋上", "hiragana": "おくじょう", "vietnamese": "Sân thượng"},
            {"kanji": "運動場", "hiragana": "うんどうじょう", "vietnamese": "Sân vận động (VẬN ĐỘNG TRƯỜNG)"},
            {"kanji": "発表会", "hiragana": "はっぴょうかい", "vietnamese": "Hội phát biểu"},
            {"kanji": "誕生日パーティー", "hiragana": "たんじょうパーティー", "vietnamese": "Tiệc sinh nhật"},
            {"kanji": "試合", "hiragana": "しあい", "vietnamese": "Trận đấu (thể thao)"},
            {"kanji": "地震", "hiragana": "じしん", "vietnamese": "Động đất"},
            {"kanji": "火事", "hiragana": "かじ", "vietnamese": "Hỏa hoạn (HỎA SỰ)"},
            {"kanji": "交通事故", "hiragana": "こうつうじこ", "vietnamese": "Sự cố, tai nạn giao thông (GIAO THÔNG SỰ CỐ)"},
            {"kanji": "花火大会", "hiragana": "はなびたいかい", "vietnamese": "Lễ hội pháo hoa"},
            {"kanji": "池", "hiragana": "いけ", "vietnamese": "Ao"},
            {"kanji": "袋", "hiragana": "ふくろ", "vietnamese": "Túi, bao"},
            {"kanji": "地図", "hiragana": "ちず", "vietnamese": "Bản đồ (ĐỊA ĐỒ)"},
            {"kanji": "買い物客", "hiragana": "かいものきゃく", "vietnamese": "Người mua sắm"},
            {"kanji": "", "hiragana": "ペット", "vietnamese": "Thú cưng"},
            {"kanji": "", "hiragana": "デパート", "vietnamese": "Trung tâm thương mại"},
            {"kanji": "たくさん", "hiragana": "たくさん", "vietnamese": "Nhiều"},
            {"kanji": "大勢", "hiragana": "おおぜい", "vietnamese": "Nhiều người"},
            {"kanji": "誰か", "hiragana": "だれか", "vietnamese": "Ai đó"},
            {"kanji": "何か", "hiragana": "なにか", "vietnamese": "Cái gì đó"},
            {"kanji": "どこか", "hiragana": "どこか", "vietnamese": "Ở đâu đó"}
        ]
    },
    {
        "id": "n5_b13",
        "title": "Bài 13: Cơ thể, Sở thích, Môn học, Màu sắc & Món ăn",
        "description": "Các bộ phận cơ thể, thể loại nhạc/phim/thể thao, môn học, màu sắc, ẩm thực Nhật và tính từ",
        "words": [
            # Body
            {"kanji": "体", "hiragana": "からだ", "vietnamese": "Cơ thể"},
            {"kanji": "背", "hiragana": "せ", "vietnamese": "Dáng, chiều cao"},
            {"kanji": "肌", "hiragana": "はだ", "vietnamese": "Da"},
            {"kanji": "毛", "hiragana": "け", "vietnamese": "Lông"},
            {"kanji": "髪の毛", "hiragana": "かみのけ", "vietnamese": "Tóc"},
            {"kanji": "頭", "hiragana": "あたま", "vietnamese": "Đầu"},
            {"kanji": "顔", "hiragana": "かお", "vietnamese": "Khuôn mặt"},
            {"kanji": "耳", "hiragana": "みみ", "vietnamese": "Tai"},
            {"kanji": "目", "hiragana": "め", "vietnamese": "Mắt"},
            {"kanji": "鼻", "hiragana": "はな", "vietnamese": "Mũi"},
            {"kanji": "口", "hiragana": "くち", "vietnamese": "Miệng"},
            {"kanji": "首", "hiragana": "くび", "vietnamese": "Cổ"},
            {"kanji": "喉", "hiragana": "のど", "vietnamese": "Họng"},
            {"kanji": "お腹", "hiragana": "おなか", "vietnamese": "Bụng"},
            {"kanji": "手", "hiragana": "て", "vietnamese": "Bàn tay"},
            {"kanji": "指", "hiragana": "ゆび", "vietnamese": "Ngón tay"},
            {"kanji": "腕", "hiragana": "うで", "vietnamese": "Cánh tay"},
            {"kanji": "足", "hiragana": "あし", "vietnamese": "Chân"},
            {"kanji": "尻尾", "hiragana": "しっぽ", "vietnamese": "Cái đuôi"},
            # Subjects & Colors
            {"kanji": "数学", "hiragana": "すうがく", "vietnamese": "Số học, toán"},
            {"kanji": "物理", "hiragana": "ぶつり", "vietnamese": "Vật lý"},
            {"kanji": "化学", "hiragana": "かがく", "vietnamese": "Hóa học"},
            {"kanji": "生物", "hiragana": "せいぶつ", "vietnamese": "Sinh vật"},
            {"kanji": "国語", "hiragana": "こくご", "vietnamese": "Quốc ngữ"},
            {"kanji": "漢字", "hiragana": "かんじ", "vietnamese": "Hán tự"},
            {"kanji": "会話", "hiragana": "かいわ", "vietnamese": "Hội thoại"},
            {"kanji": "作文", "hiragana": "さくぶん", "vietnamese": "Tập làm văn"},
            {"kanji": "文法", "hiragana": "ぶんぽう", "vietnamese": "Văn phạm"},
            {"kanji": "読解", "hiragana": "どっかい", "vietnamese": "Đọc hiểu"},
            {"kanji": "白", "hiragana": "しろ", "vietnamese": "Màu trắng"},
            {"kanji": "黒", "hiragana": "くろ", "vietnamese": "Màu đen"},
            {"kanji": "青", "hiragana": "あお", "vietnamese": "Màu xanh"},
            {"kanji": "赤", "hiragana": "あか", "vietnamese": "Màu đỏ"},
            {"kanji": "黄色", "hiragana": "きいろ", "vietnamese": "Màu vàng"},
            {"kanji": "金色", "hiragana": "きんいろ", "vietnamese": "Màu vàng kim"},
            {"kanji": "銀色", "hiragana": "ぎんいろ", "vietnamese": "Màu bạc"},
            {"kanji": "茶色", "hiragana": "ちゃいろ", "vietnamese": "Màu nâu"},
            {"kanji": "灰色", "hiragana": "はいいろ", "vietnamese": "Màu xám"},
            {"kanji": "緑", "hiragana": "みどり", "vietnamese": "Màu xanh lá cây"},
            {"kanji": "紫", "hiragana": "むらさき", "vietnamese": "Màu tím"},
            {"kanji": "", "hiragana": "ピンク", "vietnamese": "Màu hồng"},
            # Food
            {"kanji": "", "hiragana": "すし", "vietnamese": "Sushi"},
            {"kanji": "", "hiragana": "さしみ", "vietnamese": "Sashimi"},
            {"kanji": "", "hiragana": "てんぷら", "vietnamese": "Tempura"},
            {"kanji": "", "hiragana": "うどん", "vietnamese": "Mì Udon"},
            {"kanji": "", "hiragana": "そば", "vietnamese": "Mì soba"},
            {"kanji": "", "hiragana": "ラーメン", "vietnamese": "Mì Ramen"},
            {"kanji": "", "hiragana": "とんかつ", "vietnamese": "Thịt heo chiên xù"},
            {"kanji": "", "hiragana": "ぎゅうどん", "vietnamese": "Cơm thịt bò"},
            {"kanji": "", "hiragana": "おこのみやき", "vietnamese": "Bánh xèo Nhật"},
            {"kanji": "", "hiragana": "コロッケ", "vietnamese": "Bánh khoai tây rán"},
            {"kanji": "味噌汁", "hiragana": "みそしる", "vietnamese": "Súp Miso"},
            {"kanji": "", "hiragana": "おにぎり", "vietnamese": "Cơm nắm"},
            {"kanji": "", "hiragana": "すきやき", "vietnamese": "Món Sukiyaki"},
            {"kanji": "", "hiragana": "しゃぶしゃぶ", "vietnamese": "Lẩu Shabu Shabu"},
            {"kanji": "", "hiragana": "たこやき", "vietnamese": "Bạch tuộc nướng"},
            {"kanji": "", "hiragana": "なっとう", "vietnamese": "Natto (đậu tương lên men)"},
            # Verbs & Adjectives
            {"kanji": "絵を描く", "hiragana": "えをかく", "vietnamese": "Vẽ tranh", "group": 1},
            {"kanji": "風邪を引く", "hiragana": "かぜをひく", "vietnamese": "Bị cảm", "group": 1},
            {"kanji": "弾く", "hiragana": "ひく", "vietnamese": "Đánh (đàn ghita)", "group": 1},
            {"kanji": "学ぶ", "hiragana": "まなぶ", "vietnamese": "Học (tiếng Anh)", "group": 1},
            {"kanji": "使う", "hiragana": "つかう", "vietnamese": "Sử dụng (máy tính)", "group": 1},
            {"kanji": "集める", "hiragana": "あつめる", "vietnamese": "Thu thập, sưu tầm (tem)", "group": 2},
            {"kanji": "遅れる", "hiragana": "おくれる", "vietnamese": "Trễ (giờ học)", "group": 2},
            {"kanji": "出かける", "hiragana": "でかける", "vietnamese": "Đi ra ngoài", "group": 2},
            {"kanji": "出来る", "hiragana": "できる", "vietnamese": "Có thể", "group": 2},
            {"kanji": "予約する", "hiragana": "よやくする", "vietnamese": "Đặt trước (khách sạn)", "group": 3},
            {"kanji": "速い", "hiragana": "はやい", "vietnamese": "Nhanh"},
            {"kanji": "遅い", "hiragana": "おそい", "vietnamese": "Chậm, trễ"},
            {"kanji": "多い", "hiragana": "おおい", "vietnamese": "Nhiều"},
            {"kanji": "少ない", "hiragana": "すくない", "vietnamese": "Ít"},
            {"kanji": "若い", "hiragana": "わかい", "vietnamese": "Trẻ trung"},
            {"kanji": "欲しい", "hiragana": "ほしい", "vietnamese": "Muốn có"},
            {"kanji": "冷たい", "hiragana": "つめたい", "vietnamese": "Lạnh"},
            {"kanji": "便利", "hiragana": "べんり", "vietnamese": "Tiện lợi"},
            {"kanji": "不便", "hiragana": "ふべん", "vietnamese": "Bất tiện"},
            {"kanji": "好き", "hiragana": "すき", "vietnamese": "Thích"},
            {"kanji": "嫌い", "hiragana": "きらい", "vietnamese": "Ghét"},
            {"kanji": "上手", "hiragana": "じょうず", "vietnamese": "Giỏi"},
            {"kanji": "下手", "hiragana": "へた", "vietnamese": "Dở"},
            {"kanji": "得意", "hiragana": "とくい", "vietnamese": "Có khiếu, giỏi"},
            {"kanji": "苦手", "hiragana": "にがて", "vietnamese": "Dở, không thích"},
            {"kanji": "自由", "hiragana": "じゆう", "vietnamese": "Tự do"},
            # Nouns & Extended
            {"kanji": "交通", "hiragana": "こうつう", "vietnamese": "Giao thông"},
            {"kanji": "物価", "hiragana": "ぶっか", "vietnamese": "Vật giá"},
            {"kanji": "一番", "hiragana": "いちばん", "vietnamese": "Nhất"},
            {"kanji": "外国語", "hiragana": "がいこくご", "vietnamese": "Tiếng nước ngoài"},
            {"kanji": "趣味", "hiragana": "しゅみ", "vietnamese": "Sở thích"},
            {"kanji": "図書館", "hiragana": "としょかん", "vietnamese": "Thư viện"},
            {"kanji": "字", "hiragana": "じ", "vietnamese": "Chữ viết"},
            {"kanji": "気", "hiragana": "き", "vietnamese": "Tính cách, tâm trạng"},
            {"kanji": "学費", "hiragana": "がくひ", "vietnamese": "Học phí"},
            {"kanji": "渋滞", "hiragana": "じゅうたい", "vietnamese": "Kẹt xe"},
            {"kanji": "熱", "hiragana": "ねつ", "vietnamese": "Nóng sốt"},
            {"kanji": "風邪", "hiragana": "かぜ", "vietnamese": "Bị cảm"},
            {"kanji": "約束", "hiragana": "やくそく", "vietnamese": "Lời hứa, hẹn"},
            {"kanji": "用事", "hiragana": "ようじ", "vietnamese": "Việc riêng"},
            {"kanji": "彼", "hiragana": "かれ", "vietnamese": "Anh ấy"},
            {"kanji": "彼女", "hiragana": "かのじょ", "vietnamese": "Cô ấy, bạn gái"},
            {"kanji": "心", "hiragana": "こころ", "vietnamese": "Tấm lòng"},
            {"kanji": "声", "hiragana": "こえ", "vietnamese": "Tiếng, giọng nói"},
            {"kanji": "力", "hiragana": "ちから", "vietnamese": "Sức lực"},
            {"kanji": "絵", "hiragana": "え", "vietnamese": "Tranh"},
            {"kanji": "歌", "hiragana": "うた", "vietnamese": "Bài hát"},
            {"kanji": "お腹が空く", "hiragana": "おなかがすく", "vietnamese": "Đói bụng", "group": 1},
            {"kanji": "喉が渇く", "hiragana": "のどがかわく", "vietnamese": "Khát nước", "group": 1},
            {"kanji": "丸い", "hiragana": "まるい", "vietnamese": "Tròn"},
            {"kanji": "細い", "hiragana": "ほそい", "vietnamese": "Thon, ốm"},
            {"kanji": "太い", "hiragana": "ふとい", "vietnamese": "Mập"},
            {"kanji": "痛い", "hiragana": "いたい", "vietnamese": "Đau, nhức"},
            {"kanji": "だるい", "hiragana": "だるい", "vietnamese": "Uể oải"},
            {"kanji": "寂しい", "hiragana": "さびしい", "vietnamese": "Buồn, cô đơn"},
            {"kanji": "色々", "hiragana": "いろいろ", "vietnamese": "Nhiều loại"},
            {"kanji": "気持ち", "hiragana": "きもち", "vietnamese": "Cảm giác, tâm trạng"},
            {"kanji": "身長", "hiragana": "しんちょう", "vietnamese": "Chiều cao"},
            {"kanji": "体重", "hiragana": "たいじゅう", "vietnamese": "Cân nặng"},
            {"kanji": "特に", "hiragana": "とくに", "vietnamese": "Đặc biệt là"}
        ]
    },
    {
        "id": "n5_b15",
        "title": "Bài 15: Đô thị, Xã hội & So sánh",
        "description": "Dậy sớm, thông minh, đẹp trai, so sánh đô thị - nông thôn và vị trí gần xa",
        "words": [
            {"kanji": "早起きする", "hiragana": "はやおきする", "vietnamese": "Dậy sớm", "group": 3},
            {"kanji": "頭がいい", "hiragana": "あたまがいい", "vietnamese": "Thông minh"},
            {"kanji": "", "hiragana": "ハンサム", "vietnamese": "Đẹp trai"},
            {"kanji": "世界", "hiragana": "せかい", "vietnamese": "Thế giới"},
            {"kanji": "一番", "hiragana": "いちばん", "vietnamese": "Nhất"},
            {"kanji": "現在", "hiragana": "げんざい", "vietnamese": "Hiện tại"},
            {"kanji": "景気", "hiragana": "けいき", "vietnamese": "Tình hình kinh tế"},
            {"kanji": "字", "hiragana": "じ", "vietnamese": "Chữ viết"},
            {"kanji": "人口", "hiragana": "じんこう", "vietnamese": "Dân số"},
            {"kanji": "時間", "hiragana": "じかん", "vietnamese": "Thời gian"},
            {"kanji": "栄養", "hiragana": "えいよう", "vietnamese": "Dinh dưỡng"},
            {"kanji": "両方", "hiragana": "りょうほう", "vietnamese": "Cả hai"},
            {"kanji": "都市", "hiragana": "とし", "vietnamese": "Thành phố, đô thị"},
            {"kanji": "田舎", "hiragana": "いなか", "vietnamese": "Nông thôn"},
            {"kanji": "年上", "hiragana": "としうえ", "vietnamese": "Lớn tuổi hơn"},
            {"kanji": "年下", "hiragana": "としした", "vietnamese": "Nhỏ tuổi hơn"},
            {"kanji": "同じ", "hiragana": "おなじ", "vietnamese": "Giống nhau, cùng"},
            {"kanji": "", "hiragana": "エベレスト", "vietnamese": "Đỉnh Everest"},
            {"kanji": "近い", "hiragana": "ちかい", "vietnamese": "Gần (trường)"},
            {"kanji": "遠い", "hiragana": "とおい", "vietnamese": "Xa (trường)"},
            {"kanji": "店", "hiragana": "みせ", "vietnamese": "Cửa hàng"},
            {"kanji": "次", "hiragana": "つぎ", "vietnamese": "Tiếp theo"},
            {"kanji": "時々", "hiragana": "ときどき", "vietnamese": "Đôi khi, thỉnh thoảng"},
            {"kanji": "何でも", "hiragana": "なんでも", "vietnamese": "Bất cứ cái gì"}
        ]
    },
    {
        "id": "n5_b16",
        "title": "Bài 16: Động từ đời sống, Thời tiết & Cách làm (〜かた)",
        "description": "Động từ khô, sống, trở thành, nhớ; thời tiết gió/mưa; phương hướng bắc/trung/nam và mẫu 〜かた",
        "words": [
            {"kanji": "歩く", "hiragana": "あるく", "vietnamese": "Đi bộ, đi", "group": 1},
            {"kanji": "乾く", "hiragana": "かわく", "vietnamese": "(đồ giặt) Khô", "group": 1},
            {"kanji": "住む", "hiragana": "すむ", "vietnamese": "Sinh sống, sống (ở Nhật)", "group": 1},
            {"kanji": "なる", "hiragana": "なる", "vietnamese": "Trở thành, trở nên", "group": 1},
            {"kanji": "当たる", "hiragana": "あたる", "vietnamese": "Trúng (xổ số)", "group": 1},
            {"kanji": "変わる", "hiragana": "かわる", "vietnamese": "(thời tiết) Thay đổi", "group": 1},
            {"kanji": "起こる", "hiragana": "おこる", "vietnamese": "(tai nạn) Xảy ra", "group": 1},
            {"kanji": "割れる", "hiragana": "われる", "vietnamese": "(kính cửa sổ) Vỡ", "group": 2},
            {"kanji": "覚える", "hiragana": "おぼえる", "vietnamese": "Nhớ, học thuộc (Hán tự)", "group": 2},
            {"kanji": "長い", "hiragana": "ながい", "vietnamese": "Dài"},
            {"kanji": "短い", "hiragana": "みじかい", "vietnamese": "Ngắn"},
            {"kanji": "濃い", "hiragana": "こい", "vietnamese": "Đậm, đặc"},
            {"kanji": "薄い", "hiragana": "うすい", "vietnamese": "Nhạt, mờ, mỏng"},
            {"kanji": "丁寧", "hiragana": "ていねい", "vietnamese": "Lịch sự"},
            {"kanji": "客", "hiragana": "おきゃく", "vietnamese": "Khách hàng"},
            {"kanji": "半分", "hiragana": "はんぶん", "vietnamese": "Một nửa"},
            {"kanji": "お金持ち", "hiragana": "おかねもち", "vietnamese": "Giàu có"},
            {"kanji": "宝くじ", "hiragana": "たからくじ", "vietnamese": "Vé số, xổ số"},
            {"kanji": "話", "hiragana": "はなし", "vietnamese": "Câu chuyện"},
            {"kanji": "鋏", "hiragana": "はさみ", "vietnamese": "Cái kéo"},
            {"kanji": "洗濯物", "hiragana": "せんたくもの", "vietnamese": "Quần áo giặt"},
            {"kanji": "窓ガラス", "hiragana": "まどガラス", "vietnamese": "Kính cửa sổ"},
            {"kanji": "風が吹く", "hiragana": "かぜがふく", "vietnamese": "Gió thổi", "group": 1},
            {"kanji": "雨が降る", "hiragana": "あめがふる", "vietnamese": "Trời mưa", "group": 1},
            {"kanji": "雨が止む", "hiragana": "あめがやむ", "vietnamese": "Tạnh mưa", "group": 1},
            {"kanji": "安全", "hiragana": "あんぜん", "vietnamese": "An toàn"},
            {"kanji": "危険", "hiragana": "きけん", "vietnamese": "Nguy hiểm"},
            {"kanji": "一日中", "hiragana": "いちにちじゅう", "vietnamese": "Suốt cả ngày"},
            {"kanji": "北部", "hiragana": "ほくぶ", "vietnamese": "Bắc bộ"},
            {"kanji": "中部", "hiragana": "ちゅうぶ", "vietnamese": "Trung bộ"},
            {"kanji": "南部", "hiragana": "なんぶ", "vietnamese": "Nam bộ"},
            {"kanji": "首都", "hiragana": "しゅと", "vietnamese": "Thủ đô"},
            {"kanji": "空", "hiragana": "そら", "vietnamese": "Bầu trời"},
            {"kanji": "林", "hiragana": "はやし", "vietnamese": "Rừng"},
            {"kanji": "読み方", "hiragana": "よみかた", "vietnamese": "Cách đọc"},
            {"kanji": "書き方", "hiragana": "かきかた", "vietnamese": "Cách viết"},
            {"kanji": "作り方", "hiragana": "つくりかた", "vietnamese": "Cách làm, nấu"},
            {"kanji": "話し方", "hiragana": "はなしかた", "vietnamese": "Cách nói chuyện"},
            {"kanji": "勉強の仕方", "hiragana": "べんきょうのしかた", "vietnamese": "Cách học"}
        ]
    },
    {
        "id": "n5_b17",
        "title": "Bài 17: Động từ hành động & Tiếp diễn hành vi",
        "description": "Bật/tắt đèn, cầm/mang, giúp đỡ, mở/đóng cửa và mẫu V-masu + はじめる / おわる / つづける",
        "words": [
            {"kanji": "返す", "hiragana": "かえす", "vietnamese": "Trả lại (sách)", "group": 1},
            {"kanji": "出す", "hiragana": "だす", "vietnamese": "Gửi (thư), nộp, lấy", "group": 1},
            {"kanji": "取る", "hiragana": "とる", "vietnamese": "Lấy (điện thoại), ghi chú (memo)", "group": 1},
            {"kanji": "持つ", "hiragana": "もつ", "vietnamese": "Cầm, mang (hành lý)", "group": 1},
            {"kanji": "消す", "hiragana": "けす", "vietnamese": "Tắt (đèn)", "group": 1},
            {"kanji": "点ける", "hiragana": "つける", "vietnamese": "Bật (đèn)", "group": 2},
            {"kanji": "勤める", "hiragana": "つとめる", "vietnamese": "Làm việc (cho công ty)", "group": 2},
            {"kanji": "助ける", "hiragana": "たすける", "vietnamese": "Giúp đỡ (người khác)", "group": 2},
            {"kanji": "浴びる", "hiragana": "あびる", "vietnamese": "Tắm (vòi sen)", "group": 2},
            {"kanji": "閉める", "hiragana": "しめる", "vietnamese": "Đóng (cửa)", "group": 2},
            {"kanji": "開ける", "hiragana": "あける", "vietnamese": "Mở (cửa)", "group": 2},
            {"kanji": "参加する", "hiragana": "さんかする", "vietnamese": "Tham gia (cuộc thi)", "group": 3},
            {"kanji": "実家", "hiragana": "じっか", "vietnamese": "Quê nhà, nhà bố mẹ"},
            {"kanji": "海外旅行", "hiragana": "かいがいりょこう", "vietnamese": "Du lịch nước ngoài"},
            {"kanji": "体験", "hiragana": "たいけん", "vietnamese": "Trải nghiệm"},
            {"kanji": "寮", "hiragana": "りょう", "vietnamese": "Ký túc xá"},
            {"kanji": "", "hiragana": "シャワー", "vietnamese": "Vòi sen"},
            {"kanji": "", "hiragana": "コンテスト", "vietnamese": "Cuộc thi"},
            {"kanji": "遊ぶ", "hiragana": "あそぶ", "vietnamese": "Chơi, vui đùa", "group": 1},
            {"kanji": "迎える", "hiragana": "むかえる", "vietnamese": "Đón, tiếp đón", "group": 2},
            {"kanji": "始めます", "hiragana": "～はじめる", "vietnamese": "Bắt đầu làm ~"},
            {"kanji": "終わります", "hiragana": "～おわる", "vietnamese": "Làm ~ xong"},
            {"kanji": "続けます", "hiragana": "～つづける", "vietnamese": "Tiếp tục làm ~"},
            {"kanji": "文学", "hiragana": "ぶんがく", "vietnamese": "Văn học"},
            {"kanji": "楽しみ", "hiragana": "たのしみ", "vietnamese": "Mong đợi, mong chờ"},
            {"kanji": "皿", "hiragana": "おさら", "vietnamese": "Đĩa"},
            {"kanji": "提灯", "hiragana": "ちょうちん", "vietnamese": "Đèn lồng"},
            {"kanji": "", "hiragana": "バーベキュー", "vietnamese": "Tiệc nướng ngoài trời"}
        ]
    },
    {
        "id": "n5_b18",
        "title": "Bài 18: Động từ công việc, Nấu ăn & Trạng từ thứ tự",
        "description": "Làm việc ở ngân hàng, hoa nở, rút tiền, làm mất, nướng bánh, các phó từ まず/つぎに/さいごに",
        "words": [
            {"kanji": "働く", "hiragana": "はたらく", "vietnamese": "Làm việc (ở ngân hàng)", "group": 1},
            {"kanji": "咲く", "hiragana": "さく", "vietnamese": "Hoa nở", "group": 1},
            {"kanji": "剥く", "hiragana": "むく", "vietnamese": "Gọt vỏ", "group": 1},
            {"kanji": "下ろす", "hiragana": "おろす", "vietnamese": "Rút tiền", "group": 1},
            {"kanji": "無くす", "hiragana": "なくす", "vietnamese": "Làm mất (tài liệu)", "group": 1},
            {"kanji": "呼ぶ", "hiragana": "よぶ", "vietnamese": "Gọi (taxi)", "group": 1},
            {"kanji": "知る", "hiragana": "しる", "vietnamese": "Biết (số điện thoại)", "group": 1},
            {"kanji": "やる", "hiragana": "やる", "vietnamese": "Chơi bóng chày, làm", "group": 1},
            {"kanji": "投げる", "hiragana": "なげる", "vietnamese": "Ném (đá)", "group": 2},
            {"kanji": "忘れる", "hiragana": "わすれる", "vietnamese": "Quên (ngày sinh nhật)", "group": 2},
            {"kanji": "止める", "hiragana": "とめる", "vietnamese": "Dừng xe", "group": 2},
            {"kanji": "経営する", "hiragana": "けいえいする", "vietnamese": "Kinh doanh (công ty)", "group": 3},
            {"kanji": "心配する", "hiragana": "しんぱいする", "vietnamese": "Lo lắng (chuyện của tôi)", "group": 3},
            {"kanji": "返事する", "hiragana": "へんじする", "vietnamese": "Trả lời, đáp lại", "group": 3},
            {"kanji": "練習する", "hiragana": "れんしゅうする", "vietnamese": "Luyện tập", "group": 3},
            {"kanji": "大切", "hiragana": "たいせつ", "vietnamese": "Quan trọng, cần thiết"},
            {"kanji": "大丈夫", "hiragana": "だいじょうぶ", "vietnamese": "Không vấn đề gì!"},
            {"kanji": "邪魔", "hiragana": "じゃま", "vietnamese": "Cản trở, phiền hà"},
            {"kanji": "電子辞書", "hiragana": "でんしじしょ", "vietnamese": "Từ điển điện tử"},
            {"kanji": "資料", "hiragana": "しりょう", "vietnamese": "Tài liệu, tư liệu"},
            {"kanji": "石", "hiragana": "いし", "vietnamese": "Hòn đá"},
            {"kanji": "言葉", "hiragana": "ことば", "vietnamese": "Ngôn ngữ, từ"},
            {"kanji": "皮", "hiragana": "かわ", "vietnamese": "Vỏ, da"},
            {"kanji": "", "hiragana": "センター", "vietnamese": "Trung tâm"},
            {"kanji": "", "hiragana": "プール", "vietnamese": "Hồ bơi"},
            {"kanji": "", "hiragana": "カタログ", "vietnamese": "Ca-ta-lô"},
            {"kanji": "ゆっくり", "hiragana": "ゆっくり", "vietnamese": "Từ từ, thong thả"},
            {"kanji": "どうやって", "hiragana": "どうやって", "vietnamese": "Bằng cách nào"},
            {"kanji": "～のこと", "hiragana": "～のこと", "vietnamese": "Chuyện (của ~)"},
            {"kanji": "焼く", "hiragana": "やく", "vietnamese": "Nướng (bánh)", "group": 1},
            {"kanji": "混ぜる", "hiragana": "まぜる", "vietnamese": "Trộn (trứng và bột)", "group": 2},
            {"kanji": "眠い", "hiragana": "ねむい", "vietnamese": "Buồn ngủ"},
            {"kanji": "凄い", "hiragana": "すごい", "vietnamese": "Siêu thế, ghê gớm"},
            {"kanji": "うるさい", "hiragana": "うるさい", "vietnamese": "Ồn ào"},
            {"kanji": "独身", "hiragana": "どくしん", "vietnamese": "Độc thân"},
            {"kanji": "粉", "hiragana": "こな", "vietnamese": "Bột mì, bột"},
            {"kanji": "砂糖", "hiragana": "さとう", "vietnamese": "Đường ăn"},
            {"kanji": "", "hiragana": "オーブン", "vietnamese": "Lò nướng bánh"},
            {"kanji": "お大事に", "hiragana": "おだいじに", "vietnamese": "Hãy bảo trọng sức khỏe!"},
            {"kanji": "随分", "hiragana": "ずいぶん", "vietnamese": "Khá là"},
            {"kanji": "まず", "hiragana": "まず", "vietnamese": "Trước hết, trước tiên"},
            {"kanji": "次に", "hiragana": "つぎに", "vietnamese": "Kế tiếp"},
            {"kanji": "最後に", "hiragana": "さいごに", "vietnamese": "Sau cùng"},
            {"kanji": "途中に", "hiragana": "とちゅうに", "vietnamese": "Nửa chừng"},
            {"kanji": "出来上がり", "hiragana": "できあがり", "vietnamese": "Hoàn thành, làm xong"}
        ]
    },
    {
        "id": "n5_b19",
        "title": "Bài 19: Quy tắc, Giấy tờ, Đồ dùng & Hành động",
        "description": "Nhận, vội vàng, chạm vào, tuân thủ quy tắc, vứt rác, đồng phục, bảo hiểm và hạn chót 〜までに",
        "words": [
            {"kanji": "貰う", "hiragana": "もらう", "vietnamese": "Nhận (bướm quảng cáo)", "group": 1},
            {"kanji": "置く", "hiragana": "おく", "vietnamese": "Đặt, để (hành lý)", "group": 1},
            {"kanji": "急ぐ", "hiragana": "いそぐ", "vietnamese": "Vội vàng", "group": 1},
            {"kanji": "殺す", "hiragana": "ころす", "vietnamese": "Sát hại, giết (động vật)", "group": 1},
            {"kanji": "触る", "hiragana": "さわる", "vietnamese": "Chạm, đụng (máy ảnh)", "group": 1},
            {"kanji": "守る", "hiragana": "まもる", "vietnamese": "Tuân thủ (nội quy)", "group": 1},
            {"kanji": "捨てる", "hiragana": "すてる", "vietnamese": "Vứt (rác), bỏ", "group": 2},
            {"kanji": "着る", "hiragana": "きる", "vietnamese": "Mặc (đồng phục)", "group": 2},
            {"kanji": "残業する", "hiragana": "ざんぎょうする", "vietnamese": "Tăng ca", "group": 3},
            {"kanji": "ひどい", "hiragana": "ひどい", "vietnamese": "Kinh khủng, khủng khiếp"},
            {"kanji": "工場", "hiragana": "こうじょう", "vietnamese": "Nhà máy, xưởng"},
            {"kanji": "動物", "hiragana": "どうぶつ", "vietnamese": "Động vật"},
            {"kanji": "病気", "hiragana": "びょうき", "vietnamese": "Đau bệnh"},
            {"kanji": "禁煙", "hiragana": "きんえん", "vietnamese": "Việc cấm hút thuốc"},
            {"kanji": "制服", "hiragana": "せいふく", "vietnamese": "Đồng phục"},
            {"kanji": "荷物", "hiragana": "にもつ", "vietnamese": "Hành lý, đồ đạc"},
            {"kanji": "声", "hiragana": "こえ", "vietnamese": "Tiếng, giọng nói"},
            {"kanji": "～までに", "hiragana": "～までに", "vietnamese": "Trước, chậm nhất là ~"},
            {"kanji": "払う", "hiragana": "はらう", "vietnamese": "Trả tiền, thanh toán", "group": 1},
            {"kanji": "持って行く", "hiragana": "もっていく", "vietnamese": "Mang theo (hộ chiếu)", "group": 1},
            {"kanji": "連れて行く", "hiragana": "つれていく", "vietnamese": "Dẫn đi (chó)", "group": 1},
            {"kanji": "運ぶ", "hiragana": "はこぶ", "vietnamese": "Khuân, vác (hành lý)", "group": 1},
            {"kanji": "被る", "hiragana": "かぶる", "vietnamese": "Đội (nón bảo hiểm)", "group": 1},
            {"kanji": "締める", "hiragana": "ネクタイをしめる", "vietnamese": "Đeo cà vạt", "group": 2},
            {"kanji": "安心する", "hiragana": "あんしんする", "vietnamese": "Yên tâm, an tâm", "group": 3},
            {"kanji": "注意する", "hiragana": "ちゅういする", "vietnamese": "Chú ý (sức khỏe)", "group": 3},
            {"kanji": "入社する", "hiragana": "にゅうしゃする", "vietnamese": "Vào làm ở công ty", "group": 3},
            {"kanji": "新鮮", "hiragana": "しんせん", "vietnamese": "Tươi"},
            {"kanji": "番号", "hiragana": "ばんごう", "vietnamese": "Số (điện thoại, thứ tự...)"},
            {"kanji": "結婚式", "hiragana": "けっこんしき", "vietnamese": "Lễ cưới, lễ kết hôn"},
            {"kanji": "学生証", "hiragana": "がくせいしょう", "vietnamese": "Thẻ học sinh"},
            {"kanji": "保険証", "hiragana": "ほけんしょう", "vietnamese": "Thẻ bảo hiểm, sổ bảo hiểm"},
            {"kanji": "健康", "hiragana": "けんこう", "vietnamese": "Sức khỏe"},
            {"kanji": "必ず", "hiragana": "かならず", "vietnamese": "Nhất định"},
            {"kanji": "", "hiragana": "ルール", "vietnamese": "Luật lệ"},
            {"kanji": "", "hiragana": "ゴミ", "vietnamese": "Rác, bụi"},
            {"kanji": "", "hiragana": "パンフレット", "vietnamese": "Bướm quảng cáo"},
            {"kanji": "", "hiragana": "エアコン", "vietnamese": "Máy điều hòa"},
            {"kanji": "", "hiragana": "アパート", "vietnamese": "Căn hộ"},
            {"kanji": "", "hiragana": "ヨーロッパ", "vietnamese": "Châu Âu"},
            {"kanji": "", "hiragana": "ヘルメット", "vietnamese": "Nón bảo hiểm"},
            {"kanji": "", "hiragana": "ノート", "vietnamese": "Tập vở"},
            {"kanji": "", "hiragana": "ネクタイ", "vietnamese": "Cà vạt"},
            {"kanji": "", "hiragana": "スーツ", "vietnamese": "Đồ vét"}
        ]
    },
    {
        "id": "n5_b21",
        "title": "Bài 21: Cuộc sống, Đo lường & Tính chất",
        "description": "Hài hước, đo chiều dài, trễ giờ học, tham dự họp, cuộc sống, trà đạo, chiều cao/dài/nặng và tháp Skytree",
        "words": [
            {"kanji": "ユーモアがある", "hiragana": "ユーモアがある", "vietnamese": "Có tính hài hước", "group": 1},
            {"kanji": "測る", "hiragana": "はかる", "vietnamese": "Đo (chiều dài)", "group": 1},
            {"kanji": "乗る", "hiragana": "のる", "vietnamese": "Cưỡi ngựa", "group": 1},
            {"kanji": "登る", "hiragana": "のぼる", "vietnamese": "Leo núi Phú Sĩ", "group": 1},
            {"kanji": "遅れる", "hiragana": "おくれる", "vietnamese": "Trễ (giờ học)", "group": 2},
            {"kanji": "出席する", "hiragana": "しゅっせきする", "vietnamese": "Tham dự (buổi họp)", "group": 3},
            {"kanji": "外食する", "hiragana": "がいしょくする", "vietnamese": "Đi ăn ngoài", "group": 3},
            {"kanji": "生活", "hiragana": "せいかつ", "vietnamese": "Cuộc sống"},
            {"kanji": "一度", "hiragana": "いちど", "vietnamese": "Một lần"},
            {"kanji": "旅館", "hiragana": "りょかん", "vietnamese": "Lữ quán, nhà trọ"},
            {"kanji": "茶道", "hiragana": "さどう", "vietnamese": "Trà đạo"},
            {"kanji": "お弁当", "hiragana": "おべんとう", "vietnamese": "Cơm hộp"},
            {"kanji": "本当", "hiragana": "ほんとう", "vietnamese": "Sự thật"},
            {"kanji": "彼", "hiragana": "かれ", "vietnamese": "Anh ấy"},
            {"kanji": "彼女", "hiragana": "かのじょ", "vietnamese": "Cô ấy, bạn gái"},
            {"kanji": "答え", "hiragana": "こたえ", "vietnamese": "Câu trả lời"},
            {"kanji": "時々", "hiragana": "ときどき", "vietnamese": "Thỉnh thoảng"},
            {"kanji": "着物", "hiragana": "きもの", "vietnamese": "Đồ Kimono"},
            {"kanji": "高さ", "hiragana": "たかさ", "vietnamese": "Độ cao"},
            {"kanji": "長さ", "hiragana": "ながさ", "vietnamese": "Độ dài"},
            {"kanji": "重さ", "hiragana": "おもさ", "vietnamese": "Độ nặng"},
            {"kanji": "東京スカイツリー", "hiragana": "とうきょうスカイツリー", "vietnamese": "Tòa tháp Tokyo Sky Tree"},
            {"kanji": "", "hiragana": "キログラム", "vietnamese": "Kilôgam"},
            {"kanji": "", "hiragana": "インドネシア", "vietnamese": "Indonesia"},
            {"kanji": "～について", "hiragana": "～について", "vietnamese": "Về, đến..."},
            {"kanji": "多分", "hiragana": "たぶん", "vietnamese": "Có lẽ"}
        ]
    },
    {
        "id": "n5_b22",
        "title": "Bài 22: Giao tiếp, Nơi chốn & Chào hỏi hàng ngày",
        "description": "Nói lời cảm ơn, cười, khóc, nhận ra đồ quên, tra từ điển, cắm hoa, lời chào đi - về - ăn cơm",
        "words": [
            {"kanji": "お礼を言う", "hiragana": "おれいをいう", "vietnamese": "Nói lời cảm ơn", "group": 1},
            {"kanji": "笑う", "hiragana": "わらう", "vietnamese": "Cười", "group": 1},
            {"kanji": "泣く", "hiragana": "なく", "vietnamese": "Khóc", "group": 1},
            {"kanji": "開く", "hiragana": "あく", "vietnamese": "(cửa) Mở", "group": 1},
            {"kanji": "閉まる", "hiragana": "しまる", "vietnamese": "(cửa) Đóng", "group": 1},
            {"kanji": "着く", "hiragana": "つく", "vietnamese": "Đến, tới (nhà ga)", "group": 1},
            {"kanji": "落とす", "hiragana": "おとす", "vietnamese": "Đánh rơi (ví)", "group": 1},
            {"kanji": "気が付く", "hiragana": "きがつく", "vietnamese": "Nhận ra (bỏ quên đồ)", "group": 1},
            {"kanji": "気を付ける", "hiragana": "きをつける", "vietnamese": "Chú ý, cẩn thận (xe cộ)", "group": 2},
            {"kanji": "出かける", "hiragana": "でかける", "vietnamese": "Đi ra ngoài", "group": 2},
            {"kanji": "辞める", "hiragana": "やめる", "vietnamese": "Nghỉ, bỏ (việc)", "group": 2},
            {"kanji": "調べる", "hiragana": "しらべる", "vietnamese": "Tìm kiếm, tìm hiểu (thông tin), tra từ điển", "group": 2},
            {"kanji": "鍵を掛ける", "hiragana": "かぎをかける", "vietnamese": "Khóa cửa", "group": 2},
            {"kanji": "降りる", "hiragana": "おりる", "vietnamese": "Xuống (xe bus)", "group": 2},
            {"kanji": "予約する", "hiragana": "よやくする", "vietnamese": "Đặt trước (khách sạn)", "group": 3},
            {"kanji": "復習する", "hiragana": "ふくしゅうする", "vietnamese": "Ôn tập (văn phạm)", "group": 3},
            {"kanji": "見学する", "hiragana": "けんがくする", "vietnamese": "Tham quan học tập", "group": 3},
            {"kanji": "留学する", "hiragana": "りゅうがくする", "vietnamese": "Du học (Nhật Bản)", "group": 3},
            {"kanji": "安定する", "hiragana": "あんていする", "vietnamese": "(công việc) Ổn định", "group": 3},
            {"kanji": "連絡する", "hiragana": "れんらくする", "vietnamese": "Liên lạc (với tôi)", "group": 3},
            {"kanji": "挨拶をする", "hiragana": "あいさつをする", "vietnamese": "Chào hỏi", "group": 3},
            {"kanji": "寂しい", "hiragana": "さびしい", "vietnamese": "Buồn, cô đơn"},
            {"kanji": "必要", "hiragana": "ひつよう", "vietnamese": "Cấp thiết, cần thiết"},
            {"kanji": "本社", "hiragana": "ほんしゃ", "vietnamese": "Công ty mẹ"},
            {"kanji": "支社", "hiragana": "ししゃ", "vietnamese": "Công ty chi nhánh"},
            {"kanji": "単語", "hiragana": "たんご", "vietnamese": "Từ vựng"},
            {"kanji": "服", "hiragana": "ふく", "vietnamese": "Quần áo"},
            {"kanji": "体の調子", "hiragana": "からだのちょうし", "vietnamese": "Tình trạng cơ thể"},
            {"kanji": "郊外", "hiragana": "こうがい", "vietnamese": "Ngoại thành"},
            {"kanji": "祖母", "hiragana": "そぼ", "vietnamese": "Bà tôi"},
            {"kanji": "祖父", "hiragana": "そふ", "vietnamese": "Ông tôi"},
            {"kanji": "生け花", "hiragana": "いけばな", "vietnamese": "Cắm hoa"},
            {"kanji": "田舎", "hiragana": "いなか", "vietnamese": "Nông thôn, vùng quê"},
            {"kanji": "忘れ物", "hiragana": "わすれもの", "vietnamese": "Đồ bị bỏ quên"},
            {"kanji": "お祈り", "hiragana": "おいのり", "vietnamese": "Việc cầu nguyện"},
            {"kanji": "", "hiragana": "プレゼント", "vietnamese": "Quà tặng"},
            {"kanji": "", "hiragana": "クリスマス", "vietnamese": "Giáng sinh"},
            {"kanji": "", "hiragana": "パスポート", "vietnamese": "Hộ chiếu"},
            {"kanji": "", "hiragana": "ゲーム", "vietnamese": "Trò chơi"},
            {"kanji": "", "hiragana": "アルバイト", "vietnamese": "Làm thêm"},
            {"kanji": "", "hiragana": "オーストラリア", "vietnamese": "Nước Úc"},
            {"kanji": "行って来ます", "hiragana": "いってきます", "vietnamese": "Tôi đi đây (chào khi ra khỏi nhà)"},
            {"kanji": "行ってらっしゃい", "hiragana": "いってらっしゃい", "vietnamese": "Đi cẩn thận nhé (người ở nhà chào)"},
            {"kanji": "ただいま", "hiragana": "ただいま", "vietnamese": "Tôi đã về (chào khi về nhà)"},
            {"kanji": "お帰りなさい", "hiragana": "おかえりなさい", "vietnamese": "Bạn đã về đấy à"},
            {"kanji": "いただきます", "hiragana": "いただきます", "vietnamese": "Mời dùng bữa (trước khi ăn)"},
            {"kanji": "ご馳走様でした", "hiragana": "ごちそうさまでした", "vietnamese": "Cảm ơn vì bữa ăn ngon (sau khi ăn)"}
        ]
    },
    {
        "id": "n5_b23",
        "title": "Bài 23: Tặng nhận, Tiền bối & Quà tặng sự kiện",
        "description": "Động từ cho/nhận (あげる, もらう, くれる, いただく, くださる, さしあげる), lễ tốt nghiệp và quà kỷ niệm",
        "words": [
            {"kanji": "手伝う", "hiragana": "てつだう", "vietnamese": "Phụ giúp (chuyển nhà)", "group": 1},
            {"kanji": "いただく", "hiragana": "いただく", "vietnamese": "Nhận (kính ngữ của もらう)", "group": 1},
            {"kanji": "貰う", "hiragana": "もらう", "vietnamese": "Nhận (khăn tay)", "group": 1},
            {"kanji": "くださる", "hiragana": "くださる", "vietnamese": "Cho tôi, tặng tôi (kính ngữ của くれる)", "group": 1},
            {"kanji": "くれる", "hiragana": "くれる", "vietnamese": "Cho tôi, tặng tôi", "group": 2},
            {"kanji": "差し上げる", "hiragana": "さしあげる", "vietnamese": "Biếu, tặng (kính ngữ của あげる)", "group": 2},
            {"kanji": "あげる", "hiragana": "あげる", "vietnamese": "Cho, tặng (quà)", "group": 2},
            {"kanji": "紹介する", "hiragana": "しょうかいする", "vietnamese": "Giới thiệu (bạn bè)", "group": 3},
            {"kanji": "連れて来る", "hiragana": "つれてくる", "vietnamese": "Dẫn đến (đây)", "group": 3},
            {"kanji": "持って来る", "hiragana": "もってくる", "vietnamese": "Mang đến, mang theo (hành lý)", "group": 3},
            {"kanji": "先輩", "hiragana": "せんぱい", "vietnamese": "Tiền bối, người đi trước"},
            {"kanji": "後輩", "hiragana": "こうはい", "vietnamese": "Hậu bối, đàn em"},
            {"kanji": "友人", "hiragana": "ゆうじん", "vietnamese": "Người bạn"},
            {"kanji": "親友", "hiragana": "しんゆう", "vietnamese": "Bạn thân"},
            {"kanji": "卒業式", "hiragana": "そつぎょうしき", "vietnamese": "Lễ tốt nghiệp"},
            {"kanji": "お礼", "hiragana": "おれい", "vietnamese": "Quà cảm ơn, lời cảm ơn"},
            {"kanji": "日本酒", "hiragana": "にほんしゅ", "vietnamese": "Rượu Nhật"},
            {"kanji": "人形", "hiragana": "にんぎょう", "vietnamese": "Búp bê"},
            {"kanji": "携帯電話", "hiragana": "けいたいでんわ", "vietnamese": "Điện thoại di động"},
            {"kanji": "奨学金", "hiragana": "しょうがくきん", "vietnamese": "Học bổng"},
            {"kanji": "香水", "hiragana": "こうすい", "vietnamese": "Nước hoa"},
            {"kanji": "写真立て", "hiragana": "しゃしんたて", "vietnamese": "Khung ảnh"},
            {"kanji": "腕時計", "hiragana": "うでどけい", "vietnamese": "Đồng hồ đeo tay"},
            {"kanji": "お祝い", "hiragana": "おいわい", "vietnamese": "Quà mừng, lời chúc mừng"},
            {"kanji": "お土産", "hiragana": "おみやげ", "vietnamese": "Quà lưu niệm, đặc sản"},
            {"kanji": "花束", "hiragana": "はなたば", "vietnamese": "Bó hoa"},
            {"kanji": "指輪", "hiragana": "ゆびわ", "vietnamese": "Nhẫn"},
            {"kanji": "漫画", "hiragana": "まんが", "vietnamese": "Truyện tranh"},
            {"kanji": "", "hiragana": "ぬいぐるみ", "vietnamese": "Gấu bông, thú nhồi bông"},
            {"kanji": "", "hiragana": "おもちゃ", "vietnamese": "Đồ chơi"},
            {"kanji": "お粥", "hiragana": "おかゆ", "vietnamese": "Cháo"},
            {"kanji": "お強", "hiragana": "おこわ", "vietnamese": "Cơm nếp, xôi"},
            {"kanji": "餌", "hiragana": "えさ", "vietnamese": "Mồi, thức ăn cho động vật"},
            {"kanji": "", "hiragana": "ノーベル賞", "vietnamese": "Giải thưởng Nobel"},
            {"kanji": "", "hiragana": "マザーテレサ", "vietnamese": "Đức Mẹ Teresa"},
            {"kanji": "", "hiragana": "バレンタインデー", "vietnamese": "Ngày lễ tình nhân"},
            {"kanji": "", "hiragana": "ケーキ", "vietnamese": "Bánh kem"},
            {"kanji": "", "hiragana": "チョコレート", "vietnamese": "Sô cô la"},
            {"kanji": "", "hiragana": "セーター", "vietnamese": "Áo len"},
            {"kanji": "", "hiragana": "ハンカチ", "vietnamese": "Khăn tay"},
            {"kanji": "", "hiragana": "マフラー・スカーフ", "vietnamese": "Khăn choàng"},
            {"kanji": "", "hiragana": "スカート", "vietnamese": "Váy"},
            {"kanji": "", "hiragana": "ジュエリー", "vietnamese": "Trang sức"},
            {"kanji": "", "hiragana": "ピアス", "vietnamese": "Bông tai"},
            {"kanji": "", "hiragana": "ハイヒール", "vietnamese": "Giày cao gót"}
        ]
    },
    {
        "id": "n5_b24",
        "title": "Bài 24: Lời mời, Dự định, Tương lai & Giao tiếp",
        "description": "Rủ rê, xỏ giày, so sánh xưa nay, số thứ tự, tương lai và các phó từ giao tiếp",
        "words": [
            {"kanji": "誘う", "hiragana": "さそう", "vietnamese": "Mời, rủ rê", "group": 1},
            {"kanji": "履く", "hiragana": "はく", "vietnamese": "Mang (giày), mặc (quần)", "group": 1},
            {"kanji": "無くす", "hiragana": "なくす", "vietnamese": "Làm mất (cây dù)", "group": 1},
            {"kanji": "勝つ", "hiragana": "かつ", "vietnamese": "Thắng (đội Anh thắng)", "group": 1},
            {"kanji": "泊まる", "hiragana": "とまる", "vietnamese": "Trọ lại, ở lại (khách sạn)", "group": 1},
            {"kanji": "勤める", "hiragana": "つとめる", "vietnamese": "Làm việc (cho công ty)", "group": 2},
            {"kanji": "比べる", "hiragana": "くらべる", "vietnamese": "So sánh, so với (ngày xưa)", "group": 2},
            {"kanji": "眼鏡を掛ける", "hiragana": "めがねをかける", "vietnamese": "Đeo kính", "group": 2},
            {"kanji": "着る", "hiragana": "きる", "vietnamese": "Mặc áo", "group": 2},
            {"kanji": "～番目", "hiragana": "～ばんめ", "vietnamese": "Số thứ ~"},
            {"kanji": "未来", "hiragana": "みらい", "vietnamese": "Tương lai"},
            {"kanji": "約束", "hiragana": "やくそく", "vietnamese": "Lời hứa, hẹn"},
            {"kanji": "残念", "hiragana": "ざんねん", "vietnamese": "Sự đáng tiếc"},
            {"kanji": "", "hiragana": "インスタントフォー", "vietnamese": "Phở ăn liền"},
            {"kanji": "", "hiragana": "バインミー", "vietnamese": "Bánh mì"},
            {"kanji": "", "hiragana": "パーセント", "vietnamese": "Phần trăm (%)"},
            {"kanji": "久しぶり", "hiragana": "ひさしぶり", "vietnamese": "Đã lâu rồi không (gặp)"},
            {"kanji": "もちろん", "hiragana": "もちろん", "vietnamese": "Tất nhiên rồi, đương nhiên rồi"},
            {"kanji": "そろそろ", "hiragana": "そろそろ", "vietnamese": "Đã đến lúc"},
            {"kanji": "初めて", "hiragana": "はじめて", "vietnamese": "Lần đầu tiên"}
        ]
    }
]

with open('scratch/new_lessons.json', 'w', encoding='utf-8') as f:
    json.dump(lessons, f, ensure_ascii=False, indent=2)

print("Generated", len(lessons), "new lessons successfully.")
